### ISSUE TITLE
Instructions on how build the project listed in README is incomplete

### ISSUE THREAD

**Issue by atsuzaki** [cognitive-engineering-lab/rust-book#122] opened 2023-08-24 17:33 UTC
The only step mentioned in README is to installing mdbook at the `rust-lang/rust` version as advised, but running `mdbook build` shows up missing `aquascope` and `quiz` commands (and ultimately failed for I'm not sure if related reasons?).

```
2023-08-24 10:23:08 [INFO] (mdbook::book): Book building has started
2023-08-24 10:23:08 [WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "aquascope" preprocessor installed?
2023-08-24 10:23:08 [WARN] (mdbook::preprocess::cmd):   Command: mdbook-aquascope
2023-08-24 10:23:08 [WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "quiz" preprocessor installed?
2023-08-24 10:23:08 [WARN] (mdbook::preprocess::cmd):   Command: mdbook-quiz
2023-08-24 10:23:08 [INFO] (mdbook::book): Running the html backend
2023-08-24 10:23:08 [ERROR] (mdbook::utils): Error: Rendering failed
2023-08-24 10:23:08 [ERROR] (mdbook::utils):    Caused By: Unable to copy across additional CSS and JS
2023-08-24 10:23:08 [ERROR] (mdbook::utils):    Caused By: Unable to copy /Users/atsuzaki/projects/rust-book/js-extensions/packages/consent-form/dist/index.css to /Users/atsuzaki/projects/rust-book/book/js-extensions/packages/consent-form/dist/index.css
2023-08-24 10:23:08 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

I tried to `cargo install mdbook-aquascope` and `cargo install mdbook-quiz`, then proceeded to run into trouble where the aquascope is built with a diff version, and subsequently dies.
```
2023-08-24 10:21:21 [INFO] (mdbook::book): Book building has started
Warning: The aquascope plugin was built against version 0.4.34 of mdbook, but we're being called from version 0.4.28
Command failed
2023-08-24 10:21:21 [ERROR] (mdbook::utils): Error: The "aquascope" preprocessor exited unsuccessfully with exit status: 1 status
```

I reckon the correct thing to do is to not use the crates.io ver, but directly from the aquascope repo?

But alas, would really appreciate if we could have clearer build instructions for this project. (I want to help fix your bugs, if only I could build this darn thing 😭)

**Comment by willcrichton** [comment] 2023-08-25 15:35
Ah yes I haven't updated the build instructions, sorry. The best reference for this is our CI: https://github.com/cognitive-engineering-lab/rust-book/blob/main/.github/workflows/main.yml

In particular, you will need pnpm:

https://github.com/cognitive-engineering-lab/rust-book/blob/c11cef1e1deacea7ff2fa946d976fe37b062eb9b/.github/workflows/main.yml#L24-L26

And Depot:

https://github.com/cognitive-engineering-lab/rust-book/blob/c11cef1e1deacea7ff2fa946d976fe37b062eb9b/.github/workflows/main.yml#L34-L35

And Aquascope:

https://github.com/cognitive-engineering-lab/rust-book/blob/c11cef1e1deacea7ff2fa946d976fe37b062eb9b/.github/workflows/main.yml#L59-L63

And mdbook-quiz:

https://github.com/cognitive-engineering-lab/rust-book/blob/c11cef1e1deacea7ff2fa946d976fe37b062eb9b/.github/workflows/main.yml#L65-L66

Then running `cargo make watch` should build the JS dependencies and start the notebook.

**Comment by willcrichton** [comment] 2023-08-25 15:36
And any contributions would be much appreciated!

**Comment by KineticAeon** [comment] 2023-08-27 02:40
I'm trying to update the readme so that it has proper install instructions, but I've had a nightmare and a half attempting to install Aquascope. If this doesn't belong in this repo, please tell me and I'll put it in the Aquascope one instead. This is the output of `cargo make install mdbook`:

```
error[E0658]: use of unstable library feature 'is_terminal'
  --> /Users/aeon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anstream-0.5.0/src/is_terminal.rs:68:9
   |
68 |         std::io::IsTerminal::is_terminal(self)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #98070 <https://github.com/rust-lang/rust/issues/98070> for more information
   = help: add `#![feature(is_terminal)]` to the crate attributes to enable

   Compiling proc-macro-error v1.0.4
   Compiling pest v2.7.2
For more information about this error, try `rustc --explain E0658`.
error: could not compile `anstream` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

Any ideas on what to do here?

**Comment by willcrichton** [comment] 2023-08-27 04:38
@KineticAeon sorry for the troubles. Clap updated recently, and that broke the build. I just fixed that issue, so you should be able to install Aquascope.

**Comment by KineticAeon** [comment] 2023-08-27 06:50
Alright, thanks a ton. I'll get to work finishing it up tomorrow when I've got the time and submit a PR. It could end up a bit rough style-wise, but it'll work.

**Comment by KineticAeon** [comment] 2023-08-28 07:32
I've run into another error, this time involving the spellcheck module. It gives a ton of these errors:
```
Error: Cannot find module 'spellchecker'
Require stack:
- /tmp/.tmpCpFP9H.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Module.<anonymous> (/tmp/.tmpCpFP9H.cjs:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/.tmpCpFP9H.cjs' ]
}

Node.js v20.4.0
Validation failed for quiz: /home/aeon/rust-book/src/../quizzes/ch17-01-what-is-oo.toml
2023-08-28 01:26:25 [ERROR] (mdbook::utils): Error: The "quiz" preprocessor exited unsuccessfully with exit status: 1 status
```
I thought the spellcheck was a separate script, is there something I'm missing here?

**Comment by KineticAeon** [comment] 2023-08-29 05:32
Nevermind, seems like there’s a duplicate of this issue I didn’t think to check for. I’ll do its fix and hopefully have the draft instructions tested by tomorrow.

**Comment by willcrichton** [comment] 2023-08-30 14:38
@KineticAeon thanks for the attempt. I will put it on my todo list to writeup easily-replicable installation instructions.

**Comment by willcrichton** [comment] 2023-09-21 22:00
Btw @KineticAeon @atsuzaki -- I recently updated `mdbook-quiz` to eliminate some of the annoying dependencies. I also updated the requirements for `rust-book` to link to the relevant install instructions: https://github.com/cognitive-engineering-lab/rust-book#requirements

**Comment by hamirmahal** [comment] 2023-12-07 08:42
I'd also like to contribute, but I get an error.

```
rust-book (main)$ mdbook build
2023-12-07 00:41:31 [INFO] (mdbook::book): Book building has started
Aquascope failed for program:
struct User {
    active: bool,
    username: String,
    email: String,
    sign_in_count: u64,
}
fn main() {
    let user1 = User {
        email: String::from("someone@example.com"),
        username: String::from("someusername123"),
        active: true,
        sign_in_count: 1,
    };
}
with error:
error: no such command: `aquascope`

        View all installed commands with `cargo --list`

2023-12-07 00:41:49 [ERROR] (mdbook::utils): Error: The "aquascope" preprocessor exited unsuccessfully with exit status: 1 status
```

**Comment by willcrichton** [comment] 2023-12-07 16:10
@hamirmahal did you follow the linked instructions in the README to install `mdbook-aquascope`?

**Comment by hamirmahal** [comment] 2023-12-08 04:12
@willcrichton I did

```
cargo install mdbook-aquascope --locked --version 0.3.0
rustup toolchain install nightly-2023-08-25 -c rust-src rustc-dev llvm-tools-preview miri
cargo +nightly-2023-08-25 install aquascope_front --git https://github.com/cognitive-engineering-lab/aquascope --tag v0.3.0 --locked
cargo +nightly-2023-08-25 miri setup
```

as mentioned at https://github.com/cognitive-engineering-lab/aquascope#installation

and ended up with

```
...
   Compiling aquascope v0.1.0 (/home/hamir/.cargo/git/checkouts/aquascope-b3a33f8c343833b5/b5781b3/crates/aquascope)
   Compiling aquascope_front v0.1.0 (/home/hamir/.cargo/git/checkouts/aquascope-b3a33f8c343833b5/b5781b3/crates/aquascope_front)
    Finished release [optimized] target(s) in 1m 08s
  Installing /home/hamir/.cargo/bin/aquascope-driver
  Installing /home/hamir/.cargo/bin/cargo-aquascope
   Installed package `aquascope_front v0.1.0 (https://github.com/cognitive-engineering-lab/aquascope?tag=v0.3.0#b5781b39)` (executables `aquascope-driver`, `cargo-aquascope`)
hamir@hamir-desktop:~/rust-book (main)$ mdbook build
2023-12-07 16:57:19 [INFO] (mdbook::book): Book building has started
2023-12-07 16:57:29 [INFO] (mdbook::book): Running the html backend
2023-12-07 16:57:29 [ERROR] (mdbook::utils): Error: Rendering failed
2023-12-07 16:57:29 [ERROR] (mdbook::utils):    Caused By: Unable to copy across additional CSS and JS
2023-12-07 16:57:29 [ERROR] (mdbook::utils):    Caused By: Unable to copy /home/hamir/rust-book/js-extensions/packages/consent-form/dist/index.css to /home/hamir/rust-book/book/js-extensions/packages/consent-form/dist/index.css
2023-12-07 16:57:29 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

**Comment by willcrichton** [comment] 2023-12-08 05:23
@hamirmahal ah I left out some instructions. You also need to install [pnpm](https://pnpm.io/installation) and run:

```
cd js-extensions
pnpm init-repo
```

*Then* run `mdbook build`. (I added this to the README.)

**Closed** 2024-01-08 16:22 UTC

**Comment by fisher60** [comment] 2025-04-15 15:03
Hello, I have been poking at this for quite awhile, after following the instructions from the readmes and following advice from this issue, there still seem to be issues when attempting to run `mdbook build`. It seems that aquascope cannot install correctly?

```
error[E0433]: failed to resolve: use of undeclared type `String`
 --> src/main.rs:8:17
  |
8 |     let s_own = String::from("Hello world");
  |                 ^^^^^^ use of undeclared type `String`
-Ztrack-diagnostics: created at compiler/rustc_resolve/src/late/diagnostics.rs:430:36

error[E0425]: cannot find function `drop` in this scope
  --> src/main.rs:10:5
   |
10 |     drop(s_own);
   |     ^^^^ not found in this scope
-Ztrack-diagnostics: created at compiler/rustc_resolve/src/late/diagnostics.rs:430:36

Some errors have detailed explanations: E0405, E0412, E0425, E0433, E0786.
For more information about an error, try `rustc --explain E0405`.
thread 'main' panicked at crates/aquascope_front/src/plugin.rs:141:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: <aquascope_front::plugin::AquascopePlugin as rustc_plugin::plugin::RustcPlugin>::run
   5: rustc_driver_impl::catch_fatal_errors
   6: rustc_plugin::driver::driver_main
   7: aquascope_driver::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: could not compile `example` (bin "example") due to 5 previous errors

2025-04-15 10:02:12 [ERROR] (mdbook::utils): Error: The "aquascope" preprocessor exited unsuccessfully with exit status: 1 status
```
